### ISSUE TITLE
Song links not working

### ISSUE THREAD

**Issue by realduziy** [Coskon/coskmusicbot#2]
I'm not really sure if this is a bug but any time you put a link, say on Spotify, it doesnt work, Only when you type out the songs name will it work, I guess thats how the bot is meant to work but having it so you could paste a link would be a nice addition

It sends this in conole to incase this is a bug

Traceback (most recent call last):
  File "C:\Users\jdjac\OneDrive\Desktop\bot stuff\python music bot\coskmusicbot\bot.py", line 1205, in play
    vid = links[0]
          ^^^^^
UnboundLocalError: cannot access local variable 'links' where it is not associated with a value

Also, nice project I found this to really be the only bot that works well for music bots that I coded in Python. Keep up the good work.

**Comment by realduziy** [comment]
Also, this was with Spotify links; YouTube links work just fine.

**Comment by realduziy** [comment]
![image](https://github.com/Coskon/coskmusicbot/assets/106121537/8badd0db-8eac-448d-9376-d3026de6a8d3)

One more thing is that it seems to recognise the link; it just doesnt play the song

**Comment by Coskon** [comment]
Using spotify and other pages is only available in the "bot_beta.py", try downloading the last version and run "run_beta.bat" instead, and it should work.

**Comment by realduziy** [comment]
ah I see

**Comment by realduziy** [comment]
I got this when I tried the beta

>>> Command from duziy: play https://open.spotify.com/track/196y8nlOi7a5Fcd1Rihqm0?si=e465c191c83249da
Traceback (most recent call last):
  File "C:\Users\jdjac\OneDrive\Desktop\bot stuff\python music bot\coskmusicbot\bot_beta.py", line 1331, in play
    channel_to_send, CAN_REPLY = get_channel_restriction(ctx)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jdjac\OneDrive\Desktop\bot stuff\python music bot\coskmusicbot\bot_beta.py", line 348, in get_channel_restriction
    return (ctx, True) if options['restricted_to'] == 'ALL_CHANNELS' \
                          ~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'restricted_to

**Comment by Coskon** [comment]
Try removing the files PARAMETERS.txt, options_(some numbers).json and user_perms_(same numbers).json, then open run_beta.bat again.
I'll fix this so it automatically detects these errors, in this case its because your options file is outdated and doesnt have all options.

**Comment by Coskon** [comment]
Closed the issue, if more things like these keep happening even after a clean install of the last version, feel free to open it again. If you have another problem then open a new issue.
